#!/bin/bash

read -p "Are you sure delete this? (Y/N)" confirm

# make trash dir
if [ ! -d ~/trash ]
then
    mkdir ~/trash
fi

# move to ~/trash dir
if [ "$confirm" == 'Y' -o "$confirm" == 'y' ]
then
    while [ $# != 0 ]
        do
            dt=$(date +%Y%m%d_%H%M%S)
            mv -i $1 ~/trash/"$1"_"$dt"
            shift
        done
    exit 0
fi
