#!/bin/bash

read -p "Are you sure delete this? (yes/no)" confirm

# make trash dir
if [ ! -d ~/trash ]
then
    mkdir ~/trash
fi

# move to ~/trash dir
if [ "$confirm" == 'yes' -o "$confirm" == 'y' ]
then
    dt=$(date +%Y%m%d_%H%M%S)
    mkdir ~/trash/"$dt" && mv -i $@ ~/trash/"$dt"/
    exit 0
fi
