#!/bin/bash

# handle option
getopts ":y" opt
case $opt in
    y)
        confirm='y'
        shift
        ;;
    ?)
        read -p "Are you sure delete this? (Y/N)" confirm
        ;;
esac

# make trash dir
if [ ! -d ~/trash ]
then
    mkdir ~/trash
fi

# move to ~/trash dir
if [ "$confirm" == 'Y' -o "$confirm" == 'y' ]
then
    while [ $# != 0 ]
        do
            # cut filepath
	    cut=${1%/}
            cut=${cut##*/}
            # gen time
            dt=$(date +%Y%m%d_%H%M%S)
	    # move to trash
            mv -i $1 ~/trash/"$cut"_"$dt"
            shift
        done
    exit 0
fi
